name: CI

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Save
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}

  tweet:
    needs:
      - checkout
    runs-on: ubuntu-latest
    name: Send tweet
    outputs:
      json: ${{ steps.tweet.outputs.json }}
    steps:
      - name: Cache Restore
        uses: actions/cache@v2
        id: cache-restore
        with:
          path: |
            ./*
          key: ${{ github.sha }}

      - name: Send tweet
        uses: ./
        id: tweet
        with:
          app-key: ${{ secrets.TWITTER_APP_KEY }}
          app-secret: ${{ secrets.TWITTER_APP_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          tweet: "🎹 hello from the c iiiiiii!!!! 🥁"

      - name: Review the results
        run: |-
          echo "${{ steps.tweet.outputs.text }}"
